export const prod_list = [
  {
    id: 1,
    prodName_or_alt: 'Кофейная канефора',
    icon_url: '/coffee1.jpg',
    price: '$23.05',
    index: 'coffee',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum, ut a ducimus minus amet esse repudiandae in adipisci reiciendis voluptatem deleniti voluptatibus, velit eum natus, facilis cum. Dignissimos libero aspernatur placeat odit voluptate at. Magnam dicta consequuntur neque magni et eius provident aperiam inventore at atque, beatae dolor, quisquam reiciendis!',
  },
  {
    id: 2,
    prodName_or_alt: 'Кофейное зерно',
    icon_url: '/coffee2.jpg',
    price: '$24.66',
    index: 'coffee',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum, ut a ducimus minus amet esse repudiandae in adipisci reiciendis voluptatem deleniti voluptatibus, velit eum natus, facilis cum. Dignissimos libero aspernatur placeat odit voluptate at. Magnam dicta consequuntur neque magni et eius provident aperiam inventore at atque, beatae dolor, quisquam reiciendis!',
  },
  {
    id: 3,
    prodName_or_alt: 'Эфиопский аромат',
    icon_url: '/coffee3.jpg',
    price: '$9.00-19.99$',
    index: 'coffee',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum, ut a ducimus minus amet esse repudiandae in adipisci reiciendis voluptatem deleniti voluptatibus, velit eum natus, facilis cum. Dignissimos libero aspernatur placeat odit voluptate at. Magnam dicta consequuntur neque magni et eius provident aperiam inventore at atque, beatae dolor, quisquam reiciendis!',
  },
  {
    id: 4,
    prodName_or_alt: 'Кофейная чашка',
    icon_url: '/coffee4.jpg',
    price: '19.00$',
    index: 'accessories',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum, ut a ducimus minus amet esse repudiandae in adipisci reiciendis voluptatem deleniti voluptatibus, velit eum natus, facilis cum. Dignissimos libero aspernatur placeat odit voluptate at. Magnam dicta consequuntur neque magni et eius provident aperiam inventore at atque, beatae dolor, quisquam reiciendis!',
  },
  {
    id: 5,
    prodName_or_alt: 'Кофемолка',
    icon_url: '/eq0.jpg',
    price: '$13.44',
    index: 'eq',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum, ut a ducimus minus amet esse repudiandae in adipisci reiciendis voluptatem deleniti voluptatibus, velit eum natus, facilis cum. Dignissimos libero aspernatur placeat odit voluptate at. Magnam dicta consequuntur neque magni et eius provident aperiam inventore at atque, beatae dolor, quisquam reiciendis!',
  },
  {
    id: 6,
    prodName_or_alt: 'Американский кофе',
    icon_url: '/coffee6.jpg',
    price: '$14.00',
    index: 'coffee',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum, ut a ducimus minus amet esse repudiandae in adipisci reiciendis voluptatem deleniti voluptatibus, velit eum natus, facilis cum. Dignissimos libero aspernatur placeat odit voluptate at. Magnam dicta consequuntur neque magni et eius provident aperiam inventore at atque, beatae dolor, quisquam reiciendis!',
  },
  {
    id: 7,
    prodName_or_alt: 'Аксессуар "Кепка"',
    icon_url: '/coffee7.jpg',
    price: '$4.99',
    index: 'accessories',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum, ut a ducimus minus amet esse repudiandae in adipisci reiciendis voluptatem deleniti voluptatibus, velit eum natus, facilis cum. Dignissimos libero aspernatur placeat odit voluptate at. Magnam dicta consequuntur neque magni et eius provident aperiam inventore at atque, beatae dolor, quisquam reiciendis!',
  },
  {
    id: 8,
    prodName_or_alt: 'Кофейные конфеты',
    icon_url: '/coffee8.jpg',
    price: '$7.56',
    index: 'coffee',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum, ut a ducimus minus amet esse repudiandae in adipisci reiciendis voluptatem deleniti voluptatibus, velit eum natus, facilis cum. Dignissimos libero aspernatur placeat odit voluptate at. Magnam dicta consequuntur neque magni et eius provident aperiam inventore at atque, beatae dolor, quisquam reiciendis!',
  },
  {
    id: 9,
    prodName_or_alt: 'Кофемолка Hario Ceramic Coffee Mill Skerton',
    icon_url: '/eq2.jpg',
    price: '$35.00',
    index: 'eq',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum, ut a ducimus minus amet esse repudiandae in adipisci reiciendis voluptatem deleniti voluptatibus, velit eum natus, facilis cum. Dignissimos libero aspernatur placeat odit voluptate at. Magnam dicta consequuntur neque magni et eius provident aperiam inventore at atque, beatae dolor, quisquam reiciendis!',
  },
  {
    id: 10,
    prodName_or_alt: 'Капучино ICS Амаретто 1 кг',
    icon_url: '/coffee10.jpg',
    price: '$7.00',
    index: 'coffee',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum, ut a ducimus minus amet esse repudiandae in adipisci reiciendis voluptatem deleniti voluptatibus, velit eum natus, facilis cum. Dignissimos libero aspernatur placeat odit voluptate at. Magnam dicta consequuntur neque magni et eius provident aperiam inventore at atque, beatae dolor, quisquam reiciendis!',
  },
  {
    id: 11,
    prodName_or_alt: 'Кофемашина профессиональная Iberital IB7',
    icon_url: '/eq4.jpg',
    price: '$150.00',
    index: 'eq',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum, ut a ducimus minus amet esse repudiandae in adipisci reiciendis voluptatem deleniti voluptatibus, velit eum natus, facilis cum. Dignissimos libero aspernatur placeat odit voluptate at. Magnam dicta consequuntur neque magni et eius provident aperiam inventore at atque, beatae dolor, quisquam reiciendis!',
  },
  {
    id: 12,
    prodName_or_alt: 'Капучино ICS Crema Catalana 1 кг',
    icon_url: '/coffee12.jpg',
    price: '$18.00',
    index: 'coffee',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum, ut a ducimus minus amet esse repudiandae in adipisci reiciendis voluptatem deleniti voluptatibus, velit eum natus, facilis cum. Dignissimos libero aspernatur placeat odit voluptate at. Magnam dicta consequuntur neque magni et eius provident aperiam inventore at atque, beatae dolor, quisquam reiciendis!',
  },
  {
    id: 13,
    prodName_or_alt: 'Чай ICS Лимонный 1 кг',
    icon_url: '/tea1.jpg',
    price: '$15.00',
    index: 'tea',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum, ut a ducimus minus amet esse repudiandae in adipisci reiciendis voluptatem deleniti voluptatibus, velit eum natus, facilis cum. Dignissimos libero aspernatur placeat odit voluptate at. Magnam dicta consequuntur neque magni et eius provident aperiam inventore at atque, beatae dolor, quisquam reiciendis!',
  },

  {
    id: 14,
    prodName_or_alt: 'Чай ICS Персиковый 1 кг',
    icon_url: '/tea2.jpg',
    price: '$15.20',
    index: 'tea',
    text: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum, ut a ducimus minus amet esse repudiandae in adipisci reiciendis voluptatem deleniti voluptatibus, velit eum natus, facilis cum. Dignissimos libero aspernatur placeat odit voluptate at. Magnam dicta consequuntur neque magni et eius provident aperiam inventore at atque, beatae dolor, quisquam reiciendis!',
  },
];
